name: setup
description: 'Setup (Dependencies, Nodejs)'

inputs:
  node-version:
    description: Version of Node to use
    default: 18.x

  pnpm-version:
    description: Version of pnpm to use
    default: 7.x

  eas-version:
    description: Version of EAS CLI to use
    default: latest

  expo-token:
    description: Expo token to authenticate with
    required: false

runs:
  using: 'composite'
  steps:
    - name: 🏗 Setup Pnpm
      uses: pnpm/action-setup@v2
      with:
          version: ${{ inputs.pnpm-version }}

    - name: 🏗 Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
      
    - name: 🏗 Setup Expo
      uses: expo/expo-github-action@v8
      with:
        eas-version: ${{ inputs.eas-version }}
        token: ${{ inputs.expo-token }}

    - name: 📦 Install dependencies
      run: pnpm install
      shell: bash

    - name: ♻️ Restore cache
      uses: actions/cache@v3
      with:
        key: turbo-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ runner.os }}
        path: |
          node_modules/.cache/turbo
          apps/*/.turbo
          packages/*/.turbo

    # - name: Install dependencies
    #   shell: bash
    #   run: pnpm install

    # - name: Get pnpm store directory
    #   id: pnpm-cache
    #   run: |
    #     echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    # - name: ♻️ Setup pnpm cache
    #   uses: actions/cache@v3
    #   with:
    #     path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
    #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pnpm-store-
