name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build 🏗️
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: ⚡️ Build apps and packages
        run: pnpm build

      # - name: 🚀 Build mobile
      #   working-directory: apps/mobile
      #   run: eas build --non-interactive --wait --profile development --platform android

  lint:
    name: Lint ✅
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: Lint
        run: pnpm lint

  test:
    name: Test 🧪
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: Test
        run: pnpm test

  deploy:
    name: Deploy Web 🚀
    needs: [build, lint, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: ⚡️ Build apps and packages
        run: pnpm build

      - name: deploy to Netlify
        run: cd apps/web
        uses: netlify/actions/cli@master
        with:
          args: deploy --build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v2.0
      #   with:
      #     publish-dir: "./apps/web/.next"
      #     production-branch: master
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     production-deploy: true
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v2.0.0
      #   with:
      #     publish-dir: "./apps/web/.next"
      #     production-branch: main
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     deploy-message: "Deploy from GitHub Actions"
      #     enable-pull-request-comment: false
      #     enable-commit-comment: true
      #     overwrites-pull-request-comment: true
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   timeout-minutes: 1

      # - name: Deploy to Netlify
      #   uses: netlify/actions/cli@master
      #   with:
      #     working-directory: apps/web
      #     args: deploy --build --prod
      #     secrets: '["NETLIFY_ACCESS_TOKEN", "NETLIFY_SITE_ID"]'
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
